#ifndef CONSTANTS_H
#define CONSTANTS_H

// @TODO(Victor): Set the render size based on display resolution? after window init.
#define INITIAL_WINDOW_WIDTH 2560
#define INITIAL_WINDOW_HEIGHT 1440

#define MAX_DATA_POINTS 100000UL
#define MAX_REDSHIFT_GALAXIES 100000UL

#define CAMERA_NEAR_PLANE 0.1
#define CAMERA_FAR_PLANE 5000.0
#define CAMERA_FOV 85.0f
#define CAMERA_FOV_MIN 35.0f
#define CAMERA_FOV_MAX 100.0f
#define CAMERA_MOVE_SPEED 256.0f
#define CAMERA_VERTICAL_SPEED 64.0f
#define CAMERA_MOUSE_SENSITIVITY 0.1f
#define CAMERA_PITCH_LIMIT 89.0f
#define CAMERA_ORBIT_RADIUS 25.0f
#define CAMERA_ORBIT_HEIGHT 50.0f
#define CAMERA_ORBIT_SPEED 1.0f
#define CAMERA_INITIAL_ZOOM (0.8f * PI)
#define CAMERA_INITIAL_YAW 45.80f
#define CAMERA_INITIAL_PITCH 42.12f
#define CAMERA_ZOOM_SPEED 64.0f
#define CAMERA_ZOOM_MIN 0.5f
#define CAMERA_ZOOM_MAX 16.0f
#define CAMERA_SLOW_FACTOR 0.1f

#define FREE_LOOK_POS_X 13.632f
#define FREE_LOOK_POS_Y 1.377f
#define FREE_LOOK_POS_Z 9.318f
#define FREE_LOOK_TARGET_X 14.176f
#define FREE_LOOK_TARGET_Y 1.954f
#define FREE_LOOK_TARGET_Z 9.927f
#define FREE_LOOK_DIR_X 0.545f
#define FREE_LOOK_DIR_Y 0.577f
#define FREE_LOOK_DIR_Z 0.609f
#define FREE_LOOK_YAW 48.0f
#define FREE_LOOK_PITCH 35.220f

#define REDSHIFT_ORBIT_RADIUS 64.0f
#define REDSHIFT_ORBIT_SPEED 0.15f
#define REDSHIFT_PITCH_SPEED 0.08f
#define REDSHIFT_PITCH_AMPLITUDE 70.0f

#define SPHERE_MESH_RADIUS 0.25f
#define SPHERE_MESH_RINGS 4
#define SPHERE_MESH_SLICES 4
#define SPHERE_LOWPOLY_RINGS 6
#define SPHERE_LOWPOLY_SLICES 6
#define EARTH_SCALE 1.0f
#define EARTH_MODEL_SCALE 0.01f
#define COLOR_BRIGHTNESS_BOOST 1

#define COURSE_DATA_RADIUS 1024.0f
#define COURSE_DATA_SCALE 2.0f
#define ARCMIN_TO_DEGREES 60.0

#define REDSHIFT_MIN_VELOCITY_THRESHOLD 500.0
#define REDSHIFT_VELOCITY_NORMALIZATION_BASE 500.0
#define REDSHIFT_VELOCITY_NORMALIZATION_RANGE 90000.0
#define REDSHIFT_RENDER_DISTANCE_MIN 400.0
#define REDSHIFT_RENDER_DISTANCE_RANGE 4000.0
#define REDSHIFT_RENDER_DISTANCE_MAX (REDSHIFT_RENDER_DISTANCE_MIN + REDSHIFT_RENDER_DISTANCE_RANGE)
#define REDSHIFT_DISTANCE_SIZE_SCALE_MIN 4.0
#define REDSHIFT_DISTANCE_SIZE_SCALE_MAX 64.0
#define REDSHIFT_COLOR_VELOCITY_BASE 1000.0
#define REDSHIFT_COLOR_VELOCITY_RANGE 85000.0
#define REDSHIFT_COLOR_THRESHOLD_LOW 0.33
#define REDSHIFT_COLOR_THRESHOLD_MID 0.66
#define REDSHIFT_COLOR_THRESHOLD_HIGH 0.34

#define MAGNITUDE_DEFAULT_SCALE 0.6
#define MAGNITUDE_REFERENCE 12.0
#define MAGNITUDE_MAX_VALID 20.0
#define MAGNITUDE_SCALE_MIN 0.3
#define MAGNITUDE_SCALE_MAX 1.2

#define FPS_SMOOTHING_ALPHA 0.1
#define FPS_UPDATE_INTERVAL 0.5f

#define MATERIAL_SHININESS_DEFAULT 0.2f

#define FONT_LOAD_SIZE 128
#define FONT_GLYPH_COUNT 95 // ASCII 32-126 only (faster GetGlyphIndex lookup)
#define FONT_SIZE_LARGE 32
#define FONT_SIZE_MEDIUM 24

#define UI_PANEL_MARGIN 8
#define UI_PANEL_PADDING 12
#define UI_INFO_PANEL_WIDTH 340
#define UI_INFO_PANEL_HEIGHT 100
#define UI_MODE_PANEL_WIDTH 260
#define UI_MODE_PANEL_HEIGHT 32
#define UI_LEGEND_PANEL_WIDTH 260
#define UI_LEGEND_PANEL_HEIGHT 110
#define UI_HELP_PANEL_WIDTH 340
#define UI_HELP_PANEL_HEIGHT_NORMAL 194
#define UI_HELP_PANEL_HEIGHT_PAUSED 224
#define UI_DATASET_LEGEND_WIDTH 240
#define UI_DATASET_LEGEND_HEIGHT 130
#define UI_LINE_SPACING 24
#define UI_BOTTOM_HINT_HEIGHT 50
#define UI_COLOR_BAR_HEIGHT 16
#define UI_COLOR_BAR_SEGMENTS 40

#endif // CONSTANTS_H
